// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {security} from '../models';
import {macro} from '../models';
import {main} from '../models';
import {tunnel} from '../models';
import {nettools} from '../models';

export function AddFolder(arg1:string,arg2:string):Promise<model.TreeNode>;

export function AddSession(arg1:string,arg2:model.SessionProfile):Promise<model.TreeNode>;

export function BroadcastCommand(arg1:string):Promise<void>;

export function CloseTab(arg1:string):Promise<void>;

export function DeleteMacro(arg1:string):Promise<void>;

export function DeleteNode(arg1:string):Promise<model.TreeNode>;

export function DeleteSavedPassword(arg1:string):Promise<void>;

export function DeleteTunnel(arg1:string):Promise<void>;

export function DuplicateSession(arg1:string):Promise<model.TreeNode>;

export function ExecuteMacro(arg1:string,arg2:Array<string>):Promise<void>;

export function ExportSessions():Promise<string>;

export function GetAvailableSerialPorts():Promise<Array<string>>;

export function GetCustomizerConfig():Promise<security.CustomizerConfig>;

export function GetMacros():Promise<Array<macro.Macro>>;

export function GetSavedPasswords():Promise<Array<main.SavedCredential>>;

export function GetSecurityPolicy():Promise<security.SecurityPolicy>;

export function GetSessionTree():Promise<model.TreeNode>;

export function GetTunnels():Promise<Array<tunnel.TunnelConfig>>;

export function HasSavedPassword(arg1:string):Promise<boolean>;

export function ImportSessions(arg1:string):Promise<model.TreeNode>;

export function LaunchRDPSession(arg1:model.SessionProfile,arg2:string):Promise<void>;

export function LaunchSystemTool(arg1:string):Promise<void>;

export function MoveSession(arg1:string,arg2:string):Promise<model.TreeNode>;

export function NetCalculateHash(arg1:string,arg2:string):Promise<string>;

export function NetLookupDNS(arg1:string):Promise<{[key: string]: Array<string>}>;

export function NetPing(arg1:string):Promise<string>;

export function NetPortScan(arg1:string,arg2:Array<number>):Promise<Array<nettools.PortScanResult>>;

export function OpenLocalTerminal(arg1:string):Promise<string>;

export function OpenSession(arg1:model.SessionProfile,arg2:string):Promise<string>;

export function QuickConnect(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<string>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SFTPDelete(arg1:string,arg2:string):Promise<void>;

export function SFTPDownload(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SFTPList(arg1:string,arg2:string):Promise<main.SFTPListResult>;

export function SFTPMkdir(arg1:string,arg2:string):Promise<void>;

export function SFTPReadFile(arg1:string,arg2:string):Promise<string>;

export function SFTPRename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SFTPUpload(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SFTPWriteFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveCustomizerConfig(arg1:security.CustomizerConfig):Promise<void>;

export function SaveMacro(arg1:macro.Macro):Promise<void>;

export function SaveSecurityPolicy(arg1:security.SecurityPolicy):Promise<void>;

export function SaveSessionPassword(arg1:string,arg2:string):Promise<void>;

export function SaveTunnel(arg1:tunnel.TunnelConfig):Promise<void>;

export function SelectDownloadDest(arg1:string):Promise<string>;

export function SelectPrivateKeyFile():Promise<string>;

export function SelectUploadFile():Promise<string>;

export function StartTunnel(arg1:string,arg2:string):Promise<void>;

export function StopTunnel(arg1:string):Promise<void>;

export function ToggleFolder(arg1:string,arg2:boolean):Promise<model.TreeNode>;

export function UpdateFolder(arg1:string,arg2:string):Promise<model.TreeNode>;

export function UpdateSession(arg1:model.SessionProfile):Promise<model.TreeNode>;

export function WriteToTerminal(arg1:string,arg2:string):Promise<void>;
